### PR TITLE
Akka Upgrade for HAProxy compatibility

### PR DESCRIPTION
**Pull request by pfcoperez**
## Description

This PR upgrades Akka version to 2.4.9 thus making possible to connect from a driver instance to a Crossdataserver behind a HAProxy load balancer as well as docker images with redirected addresses or ports.

### CODE REVIEW

**Comment by pianista215** [comment]
:+1:

**Comment by darroyocazorla** [comment]
Use a stable akka version (2.4.8?)

**Comment by darroyocazorla** [comment]
Are the ssl options included in server application conf still valid? Please, update the doc if needed

**Comment by darroyocazorla** [comment]
Update the changelog

**Pull request merged**
