### PR TITLE
[CROSSDATA-192] [CONFIG] Usage of environment variables

### PR DESCRIPTION
**Pull request by miguel0afd**
Environment variables to configure the Driver & Server

### CODE REVIEW

**Comment by miguel0afd** [comment]
Adding the documentation to Confluence. I'll post the link shortly

**Comment by miguel0afd** [comment]
Documentation added:

https://stratio.atlassian.net/wiki/display/CROSSDATA/5.+Configuration

**Comment by luismcl** [comment]
looks good to me

**Comment by hdominguez1989** [comment]
+1

**Pull request merged**
