### PR TITLE
Upgrade of datasources for release 1.3.0

### PR DESCRIPTION
**Pull request by miguel0afd**
## Description

- Upgrade of Cassandra & ES datasource
- Scala cross build changed from 2.11 to 2.10

### CODE REVIEW

**Comment by miguel0afd** [comment]
@hdominguez1989 & @darroyocazorla, please, review this PR again

**Comment by darroyocazorla** [comment]
LGTM. In order to see if C* has solved the pushdown bug, can you try to set pushdown to 'true'?

**Comment by miguel0afd** [comment]
@darroyocazorla I cherry-picked the tests of the master branch related to https://stratio.atlassian.net/browse/CROSSDATA-496 and changed the pushdown to true and all the tests  pass now. Anyway, please, take a look to the last changes

**Comment by darroyocazorla** [comment]
:+1:

**Comment by hdominguez1989** [comment]
+1

**Pull request merged**
